tasks:
  - init: |
      flutter --version
      flutter channel dev
      flutter config --enable-web
      cd tianhaoz
      flutter pub get
      cd ..
      cd packages
      cd homepage_layout
      flutter pub get
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
    addLabel: true
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - Dart-Code.dart-code@3.8.1:+5Rq24Mq46eJa5w39WY0bA==
    - Dart-Code.flutter@3.8.1:cytqQi/+kpu802ZOaJwayw==